[phases.setup]
nixPkgs = ['python311', 'nodejs-18_x']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r server/requirements.txt',  
    'cd client && npm install'
]

[phases.build]
cmds = ['cd client && npm run build']

[start]
cmd = 'python server/run.py'